name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: "./hellodocker/VERSION"
          property: "version"
      - name: Current version
        run: echo ${{ steps.read_property.outputs.value }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thomasjay/hellodocker
          tag_with_ref: true
