name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: "./hellodocker/VERSION"
          property: "version"
      - name: Current version
        run: echo ${{ steps.read_property.outputs.value }}
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.1
        with:
          current-version: ${{ steps.read_property.outputs.value }}
          version-fragment: "bug"
      - name: New version
        run: echo ${{ steps.bump_version.outputs.next-version }}
      - name: Remove existing version file
        uses: JesseTG/rm@v1.0.0
        with:
          path: "./hellodocker/VERSION"
      - name: Write new version
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: "./hellodocker/VERSION"
          property: "version"
          value: ${{ steps.bump_version.outputs.next-version }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.bump_version.outputs.next-version }}
      - name: Git commit changes version number
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token: ${{ secrets.TOKEN }}
          message: "Updated version to ${{ steps.bump_version.outputs.next-version }}"
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.0.0
        with:
          path: "./hellodocker/VERSION"
          property: "version"
      - name: Current version
        run: echo ${{ steps.read_property.outputs.value }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thomasjay/hellodocker:${{ steps.bump_version.outputs.next-version }}
          tags: ${{ steps.bump_version.outputs.next-version }}
          tag_with_ref: false
